[project]
name = "SiYi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi-mqtt>=2.2.0",
    "fastapi[standard]>=0.121.0",
    "pydantic-settings>=2.11.0",
    "pytest>=8.4.2",
    "pytest-asyncio>=1.2.0",
    "sqlmodel>=0.0.27",
    "structlog>=25.5.0",
]
